site_name: Knowledge Base
site_url: https://kb.subhajitbhar.com/
site_description: A simple knowledge base blog
site_author: Subhajit Bhar
extra:
  meta:
    - name: author
      content: Subhajit Bhar
    - name: robots
      content: index, follow
    - name: keywords
      content:
        Subhajit Bhar, freelance data scientist, OCR, NLP, LLM, RAG, knowledge
        base, python, programming, tutorials
    - name: Publisher
      content: Subhajit Bhar
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
    accent: black
  #   toggle:
  #     icon: material/brightness-7
  #     name: Switch to dark mode
  # - scheme: slate
  #   primary: indigo
  #   accent: indigo
  #   toggle:
  #     icon: material/brightness-4
  #     name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.footer
    # - navigation.indexes
    # - navigation.instant
  # - navigation.top
  # - navigation.tracking
extra_css:
  - assets/stylesheets/custom.css
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
watch:
  - .
copyright: Copyright &copy; 2025 Subhajit Bhar
